### PR TITLE
[FEAT] Switch to Webpack

### PR DESCRIPTION
**Pull request by pzuraq**
This PR switches to Webpack for builds. I'm doing some work on this theme to customize it for my own blog, and noticed that some of the infrastructure felt a little dated. Specifically, didn't want to include Jquery since it's not really utilized all that much, and I wanted to switch to PrismJS, etc. I started playing around and realized it would be much easier to iterate with a more modern build system too, and figured that might help things out in general.

The setup is pretty simple, this is my first time using Webpack actually so I may have done things a little off 😛 I also switched to Yarn from NPM, since I've found it's much faster in general, but can change it back if you prefer.

If you prefer not to have these changes just let me know, I can work on my own fork instead! Thanks for all the great work going into this theme, loving it so far 😄

### CODE REVIEW

**Comment by pzuraq** [comment]
Went over this PR this morning with fresh eyes and made a few more updates:

* The `fitvids` package in NPM is not the actual Jquery plugin it turns out. I opted to replace it with [Reframe.js](https://github.com/dollarshaveclub/reframe.js/), which is a bit more modern. I was hoping to save this for the next PR, but it seems like there isn't an easy way to add the original FitVids, and the update is pretty small.
* I forgot to mention this before, but I also removed the Jquery History and NProgress plugins. I couldn't find any references to them in the code, so I figured it was safe to do so. Let me know if not, can add them back!
* I added a Zip plugin to the build that builds all of the assets into a convenient uploadable zip file in production! Unfortunately, it can only work on assets that go through Webpack. So, I moved all the theme files into `src` and had Webpack move them over to the final `dist` dir. This 

  This does balloon the size of this PR quite a bit, but I think it also makes the setup a bit cleaner in some ways. I added instructions for "installing" the theme locally for development with symlinks, so far it works pretty well on my machine. It also means we can add the `dist` directory to gitignore, and remove `assets` altogether, so less duplication!
* Webpack was pulling in _all_ of the HighlightJS languages, making the built JS 600kb after minification 😱 I added [WebpackBundleAnalyzer](https://github.com/webpack-contrib/webpack-bundle-analyzer) to make sure that doesn't happen again by accident, and added a quick environment variable that can be used to launch it (see the README). The solution was to include the individual languages, which I did based on the languages that [HighlightJS](https://highlightjs.org/download/) says are available in its default bundle.

**Comment by zutrinken** [comment]
@pzuraq that looks pretty sweet. I haven't worked with Webpack myself either, but I'm happy to switch. Two things though:

I prefer a build inside the repo. Else a lot of non-devs that download the master repo instead of going to the release page will go nuts ... and I don't want to give support for that. Another Idea would be a download link in the readme and always add a zip to the release. Not sure here. Also that makes it more complicated for development in general, if the repo doesn't work directly inside the content folder, or am I wrong?

NProgress is used for a reading progress shown at top of window. Doesn't have to be NProgress but I want to keep that feature.

Thanks for your great work!

**Comment by pzuraq** [comment]
👍 I'll see what I can do to get it to get it flattened back up, hadn't considered that people might just be cloning directly to their Ghost instance. Worse comes to worst, I may just have to write a custom plugin/task for building the zip file 😛 

For the progress bar, forgive me if I'm wrong, but I think it works without NProgress? At least, I tested it after removing NProgress, and rewrote that section of the code in #52 as well, and it seems to work on its own pretty well. Maybe I'm missing something though.

**Comment by pzuraq** [comment]
Another thought before I start doing that actually, would it make sense to have a `dist` branch or something that users could track instead of master? Would be possible to setup Travis or something to push to that branch automatically whenever changes are made. Alternatively, we could move the "main" branch to develop, and have `master` be just the built theme.

If not no worries, just a thought!

**Comment by tedserbinski** [comment]
Hi bumping this!

I'm modifying Attila (amazing btw!) and after I got it setup in Git I realized there were compiled files. 

Makes sense for people that download. But then opposite for techies -- have to remove ;-)

Any work being done in this area? I want to explore the separation of build process from the build itself for those that download.

**Comment by tedserbinski** [comment]
Another idea. 

Have master branch include full compiled assets. 

And a build/dev branch for developers to hack and fork and contribute back too. 

That perhaps could be the simplest. 

Just opinion from a new perspective using this open source project.

**Comment by pascalandy** [comment]
If I can help, I'll be glad to work on a **Github Actions**. Just share:

- commands to compiles
- commands to test
- where is the output (dir or a zip)

You can see the [CI I use](https://github.com/firepress-org/ghostfire/blob/master/.github/workflows/build.yml) for site on  play-with-ghost.com

Cheers!
P

**Pull request closed without merging**
