### PR TITLE
Add Commento, Buttondown and Support for a Table Of Contents

### PR DESCRIPTION
**Pull request by bcye**
I forked this a while ago and added support for Commento, Buttondown and Table Of Contents. I tried to adhere as much as possible to the existing design and documented all changes and made them configurable (see README).

I think it might make a great addition to this repo too.

### CODE REVIEW

**Comment by zutrinken** [comment]
@bcye Thanks for your PR! I like the implementation on your blog, but I will not merge it into the main repo. I don't want to support more third party services in the future. I even plan to remove the Disqus option and switch to a simple placeholder in the template. Else I and up with adding support for too many.

`Table Of Contents` on the other hand looks pretty solid. I'll have a look into that another time. Just if you feel like it, you could create a separate PR only for this feature.

Glad this theme works for you :)

**Comment by bcye** [comment]
@zutrinken Sure can create another PR. Are you still working on the members integration? Would consider working on/finishing that, as it would really allow many more use cases for this theme.

**Comment by zutrinken** [comment]
The `members` branch needs some small touch ups and some final testing. Probably finish that by the end of this year. Unfortunately I don't have a roadmap or list that's left to do. But I'm happy for every support and additions to it!

**Comment by bcye** [comment]
That's great to hear!

**Pull request closed without merging**
